\set ON_ERROR_STOP on

-- Schema-only setup for InvoiceDoc2 (Lab 7 baseline)
-- Safe to run multiple times: creates missing tables and indexes only.
-- For Lab 8 changes (sales_person + invoice FK), run: 002_lab8_sales_person.sql

create table if not exists country (
  id bigint primary key generated by default as identity,
  created_at timestamp default now(),
  code text unique not null,
  name text not null
);

create table if not exists units (
  id bigint primary key generated by default as identity,
  created_at timestamp default now(),
  code text unique not null,
  name text not null
);

create table if not exists customer (
  id bigint primary key generated by default as identity,
  created_at timestamp default now(),
  code text unique not null,
  name text not null,
  address_line1 text,
  address_line2 text,
  country_id bigint references country(id) on delete restrict on update cascade,
  credit_limit numeric(12,2)
);

create table if not exists product (
  id bigint primary key generated by default as identity,
  created_at timestamp default now(),
  code text unique not null,
  name text not null,
  units_id bigint references units(id) on delete restrict on update cascade,
  unit_price numeric(12,2)
);

create table if not exists invoice (
  id bigint primary key generated by default as identity,
  created_at timestamp default now(),
  invoice_no text unique not null,
  invoice_date date,
  customer_id bigint references customer(id) on delete restrict on update cascade,
  total_amount numeric(12,2),
  vat numeric(12,2),
  amount_due numeric(12,2)
);

create table if not exists invoice_line_item (
  id bigint primary key generated by default as identity,
  created_at timestamp default now(),
  invoice_id bigint not null references invoice(id) on delete cascade on update cascade,
  product_id bigint not null references product(id) on delete restrict on update cascade,
  quantity numeric(12,2),
  unit_price numeric(12,2),
  extended_price numeric(12,2),
  unique (invoice_id, product_id)
);

create index if not exists idx_invoice_date on invoice(invoice_date);
create index if not exists idx_line_invoice on invoice_line_item(invoice_id);
create index if not exists idx_line_product on invoice_line_item(product_id);
