\set ON_ERROR_STOP on

-- Lab 8 incremental migration: add sales_person and optional invoice relationship.

create table if not exists sales_person (
  id bigint primary key generated by default as identity,
  created_at timestamp default now(),
  code text unique not null,
  name text not null,
  start_work_date date
);

alter table invoice
  add column if not exists sales_person_id bigint references sales_person(id)
    on delete set null
    on update cascade;

-- Sample sales persons for LoV lookup in the invoice form.
INSERT INTO sales_person (id, created_at, code, name, start_work_date)
  VALUES (1, '2026-01-01 00:00:00+00', 'SP001', 'Anan Srisuwan', '2023-01-15') ON CONFLICT DO NOTHING;
INSERT INTO sales_person (id, created_at, code, name, start_work_date)
  VALUES (2, '2026-01-01 00:10:00+00', 'SP002', 'Nida Kongsiri', '2023-03-01') ON CONFLICT DO NOTHING;
INSERT INTO sales_person (id, created_at, code, name, start_work_date)
  VALUES (3, '2026-01-01 00:20:00+00', 'SP003', 'Preecha Thamrong', '2023-05-10') ON CONFLICT DO NOTHING;
INSERT INTO sales_person (id, created_at, code, name, start_work_date)
  VALUES (4, '2026-01-01 00:30:00+00', 'SP004', 'Suda Rattanakul', '2023-07-18') ON CONFLICT DO NOTHING;
INSERT INTO sales_person (id, created_at, code, name, start_work_date)
  VALUES (5, '2026-01-01 00:40:00+00', 'SP005', 'Chaiwat Boonmee', '2023-09-25') ON CONFLICT DO NOTHING;
INSERT INTO sales_person (id, created_at, code, name, start_work_date)
  VALUES (6, '2026-01-01 00:50:00+00', 'SP006', 'Mali Intarakorn', '2023-11-02') ON CONFLICT DO NOTHING;
INSERT INTO sales_person (id, created_at, code, name, start_work_date)
  VALUES (7, '2026-01-01 01:00:00+00', 'SP007', 'Krit Chantarangsu', '2024-01-08') ON CONFLICT DO NOTHING;
INSERT INTO sales_person (id, created_at, code, name, start_work_date)
  VALUES (8, '2026-01-01 01:10:00+00', 'SP008', 'Pimchanok Viroj', '2024-02-14') ON CONFLICT DO NOTHING;
INSERT INTO sales_person (id, created_at, code, name, start_work_date)
  VALUES (9, '2026-01-01 01:20:00+00', 'SP009', 'Thanakorn Yimyam', '2024-04-22') ON CONFLICT DO NOTHING;
INSERT INTO sales_person (id, created_at, code, name, start_work_date)
  VALUES (10, '2026-01-01 01:30:00+00', 'SP010', 'Orathai Panyasak', '2024-06-05') ON CONFLICT DO NOTHING;

SELECT setval(pg_get_serial_sequence('sales_person', 'id'), coalesce(max(id), 0) + 1, false) FROM sales_person;
