\set ON_ERROR_STOP on

-- Migration: Individual Lab 3 — line-level discounts, header totals rework, configuration table
-- Run this to upgrade a Lab 2 database to Lab 3.
-- Safe to rerun: uses IF NOT EXISTS, idempotent DO blocks for RENAME, and ON CONFLICT DO NOTHING.
-- Example usage: psql $DATABASE_URL -f database/sql/004_invoice_lab3_delta.sql

-- Step 1: invoice_line_item — add 3 discount fields
alter table invoice_line_item
  add column if not exists line_discount_percent numeric(5,4) not null default 0,
  add column if not exists line_discount_amount  numeric(12,2) not null default 0,
  add column if not exists line_net_price        numeric(12,2);

-- Step 2: invoice — rename total_amount -> total_price (idempotent)
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.columns
             WHERE table_name='invoice' AND column_name='total_amount') THEN
    ALTER TABLE invoice RENAME COLUMN total_amount TO total_price;
  END IF;
END $$;

-- Step 3: invoice — rename vat -> vat_amount (idempotent)
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.columns
             WHERE table_name='invoice' AND column_name='vat') THEN
    ALTER TABLE invoice RENAME COLUMN vat TO vat_amount;
  END IF;
END $$;

-- Step 4: invoice — add new totals columns
alter table invoice
  add column if not exists total_discount numeric(12,2) not null default 0,
  add column if not exists net_price      numeric(12,2),
  add column if not exists vat_percent    numeric(5,4) not null default 0.07;

-- Step 5: configuration table (holds system defaults like vat_percent)
create table if not exists configuration (
  id          bigint primary key generated by default as identity,
  created_at  timestamp default now(),
  vat_percent numeric(5,4) not null default 0.07
);

insert into configuration (id, vat_percent)
values (1, 0.07)
on conflict (id) do nothing;

SELECT setval(pg_get_serial_sequence('configuration', 'id'), coalesce(max(id), 0) + 1, false) FROM configuration;

-- Step 6: backfill derived fields for existing rows (so reports don't break)
update invoice_line_item
   set line_net_price = extended_price
 where line_net_price is null;

update invoice
   set net_price = total_price
 where net_price is null;
