\set ON_ERROR_STOP on

ALTER TABLE invoice_line_item
  ADD COLUMN IF NOT EXISTS line_discount_percent  numeric(5,2)  NOT NULL DEFAULT 0.00,
  ADD COLUMN IF NOT EXISTS line_discount_amount   numeric(14,2) NOT NULL DEFAULT 0.00,
  ADD COLUMN IF NOT EXISTS line_net_price         numeric(14,2) NOT NULL DEFAULT 0.00;

UPDATE invoice_line_item
  SET line_net_price = extended_price
  WHERE line_discount_amount = 0 AND extended_price IS NOT NULL;

ALTER TABLE invoice
  ADD COLUMN IF NOT EXISTS vat_rate        numeric(5,4)  NOT NULL DEFAULT 0.07,
  ADD COLUMN IF NOT EXISTS total_price     numeric(14,2),
  ADD COLUMN IF NOT EXISTS total_discount  numeric(14,2) NOT NULL DEFAULT 0.00,
  ADD COLUMN IF NOT EXISTS vat_amount      numeric(14,2);

UPDATE invoice SET total_price = total_amount  WHERE total_price IS NULL;
UPDATE invoice SET vat_amount  = vat           WHERE vat_amount  IS NULL;

CREATE TABLE IF NOT EXISTS configuration (
  id     bigint primary key generated by default as identity,
  key    text unique not null,
  value  text not null
);
INSERT INTO configuration (key, value) VALUES ('vat_percent', '7') ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('configuration', 'id'), coalesce(max(id), 0) + 1, false) FROM configuration;
