\set ON_ERROR_STOP on

-- Migration: Individual Lab 4 — Receipt (customer payment) module
-- Adds receipt header, receipt line items, and a helper view used by the
-- receipt form's Invoice LoV and the two new reports.
-- Safe to rerun: uses IF NOT EXISTS + CREATE OR REPLACE VIEW.
-- Example usage: psql $DATABASE_URL -f database/sql/005_invoice_lab4_delta.sql

-- Step 1: receipt (header)
create table if not exists receipt (
  id              bigint primary key generated by default as identity,
  created_at      timestamp default now(),
  receipt_no      text unique not null,
  receipt_date    date not null,
  customer_id     bigint not null references customer(id) on delete restrict on update cascade,
  payment_method  text not null check (payment_method in ('cash','bank_transfer','check')),
  payment_notes   text,
  total_received  numeric(12,2) not null default 0
);

create index if not exists idx_receipt_customer on receipt(customer_id);
create index if not exists idx_receipt_date     on receipt(receipt_date);

-- Step 2: receipt_line_item
create table if not exists receipt_line_item (
  id                   bigint primary key generated by default as identity,
  created_at           timestamp default now(),
  receipt_id           bigint not null references receipt(id)  on delete cascade  on update cascade,
  invoice_id           bigint not null references invoice(id)  on delete restrict on update cascade,
  amount_received_here numeric(12,2) not null check (amount_received_here >= 0),
  unique (receipt_id, invoice_id)
);

create index if not exists idx_rli_receipt on receipt_line_item(receipt_id);
create index if not exists idx_rli_invoice on receipt_line_item(invoice_id);

-- Step 3: view used by receipt screen LoV + reporting
--   amount_received = total received across ALL receipts for an invoice
--   amount_remain   = amount_due - amount_received
create or replace view invoice_received_view as
select
  i.customer_id,
  i.id         as invoice_id,
  i.invoice_no,
  i.amount_due,
  coalesce(sum(rli.amount_received_here), 0)                               as amount_received,
  i.amount_due - coalesce(sum(rli.amount_received_here), 0)                 as amount_remain
from invoice i
left join receipt_line_item rli on rli.invoice_id = i.id
group by i.id, i.customer_id, i.invoice_no, i.amount_due;
