-- create payment
create table if not exists payment (
    id bigint primary key generated by default as identity,
    invoice_id bigint not null references invoice(id) on delete cascade,
    payment_date date not null,
    amount numeric(12,2) not null,
    method text,
    note text
);

-- seed data
INSERT INTO payment (id, invoice_id, payment_date, amount, method, note)
VALUES (1, 2, '2026-03-01', 1500.00, 'bank_transfer', NULL)
ON CONFLICT DO NOTHING;

INSERT INTO payment (id, invoice_id, payment_date, amount, method, note)
VALUES (2, 3, '2026-03-02', 3200.00, 'cash', NULL)
ON CONFLICT DO NOTHING;